### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by albertm805** [albertm805/magmastore#57]
## Description:
- The about us page should have the necessary content as in the mockup
- This information will be replaced by the about us section content in the `magmalabs.io/about-us`

**Comment by mariana-ochoa** [comment]
@albertm805 please check the line-height of the paragraphs, these are different from the ones in the mockups.
http://take.ms/zVkcQ

**Comment by albertm805** [comment]
@mariana-ochoa Thank you, this is fixed.

**Comment by mariana-ochoa** [comment]
@albertm805  I'm still unable to see this changes in the page
